name: Release
run-name: Automate release using semantic-release
on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/setup@bf5bfae7d43e2b2b1191383f5005cd3fb69b848d # v2.0.2
        with:
          runtime: node@22
          install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
